defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:

development:
  <<: *defaults
  database: skg

production:
  <<: *defaults
  database: skg

test:
  <<: *defaults
  database: skg_test
